models.py
from flask_sqlalchemy import SQLAlchemy
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin

db = SQLAlchemy()

#課題テーブル
class Task(db.Model):
    
    __tablename__ = 'tasks'

    id = db.Column(db.Integer,primary_key=True,autoincrement=True)
    
    task_title = db.Column(db.String(50),nullable=False)
    
    task_content = db.Column(db.Text)
    
    is_completed = db.Column(db.Boolean,default=False)
    
    def __str__(self):
        return f'課題ID:{self.id} タイトル:{self.task_title} 課題内容：{self.task_content} 完了フラグ:{self.is_completed}'
    
#ユーザーテーブル
class User(db.Model,UserMixin):
    __tablename__ = 'users'
    
    id = db.Column(db.Integer,primary_key=True,autoincrement=True) 
    
    username = db.Column(db.String(30),unique=True,nullable=False)
    
    password = db.Column(db.String(20),nullable=False)
    
    def set_password(self,password):
        
        self.password = generate_password_hash(password)
        
    def check_password(self,password):
        
        return check_password_hash(self.password,password)
        
        

forms.py
from collections.abc import Mapping, Sequence
from typing import Any
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SubmitField,PasswordField
from wtforms.validators import DataRequired,Length,ValidationError
from models import Task,User

#新規課題登録用フォーム
class TaskForm(FlaskForm):
    task_title = StringField('課題タイトル:',validators=[DataRequired('課題タイトルは必須入力です。'),
                                                   Length(max=30,message='課題タイトルは30文字以下で入力してください。')])
    task_content = TextAreaField('内容:',validators=[DataRequired('内容は必須入力です')])
    
    #登録ボタン
    submit = SubmitField('登録')
    
    #更新ボタン
    update = SubmitField('更新')
    
    def validate_task_title(self,task_title):
        task = Task.query.filter_by(task_title=task_title.data).first()
        
        if task:
            raise ValidationError(f"課題タイトル'{task_title.data}'は既に登録されています。別の課題タイトルを入力してください。")

#ログイン用フォーム     
class LoginForm(FlaskForm):
    username = StringField('ユーザー名',validators=[DataRequired('ユーザー名は必須入力です。')])
    
    password = PasswordField('パスワード',validators=[Length(8,20,'パスワードは8文字以上、20文字以内です。')])
    
    submit = SubmitField('ログイン')
    
#サインアップ用フォーム
class SignUpForm(LoginForm):
    
    submit = SubmitField('ユーザー登録')
    
    def validate_username(self,username):
        user = User.query.filter_by(username=username.data).first()
        
        if user:
            raise ValidationError('そのユーザー名は既に使用されています。別のユーザー名で登録してください。')
    
    

app.py
from flask import Flask
from flask_migrate import Migrate
from models import db,User
from flask_login import LoginManager
from auth.views import auth_bp
from task.views import task_bp

app = Flask(__name__)

#設定ファイル読込
app.config.from_object("config.Config")

db.init_app(app)

migrate = Migrate(app,db)

login_manager = LoginManager()

login_manager.init_app(app)

login_manager.login_message = 'ログインされていません。ログイン画面よりログインしてください。'

login_manager.login_view = 'auth.login'

app.register_blueprint(auth_bp)
app.register_blueprint(task_bp)

@login_manager.user_loader
def load_user(user_id):
    
    return User.query.get(int(user_id))

if __name__ == '__main__':
    app.run()

task/views.py
'''
課題の一覧表示、CRUD管理
'''
from flask import Blueprint,render_template,request,redirect,url_for,flash
from models import db, Task,User
from forms import TaskForm,LoginForm,SignUpForm
from flask_login import login_user,logout_user,login_required

#課題管理機能のBlueprint
task_bp = Blueprint('task',__name__,url_prefix='/task')
    
#一覧
@task_bp.route('/')
@login_required
def index():
    #未完了課題一覧
    uncompleted_tasks = Task.query.filter_by(is_completed=False).all()
    
    #完了課題一覧
    completed_tasks = Task.query.filter_by(is_completed=True).all()
    
    #一覧画面に遷移
    return render_template('task/index.html',uncompleted_tasks=uncompleted_tasks,completed_tasks=completed_tasks)

#登録
@task_bp.route('/new',methods=['GET','POST'])
@login_required
def new_task():
    #POSTの場合
    form = TaskForm()
    
    #バリデーションチェック
    if form.validate_on_submit():
        #新規登録課題のタイトルを取り出す
        task_title = form.task_title.data
        
        #新規登録課題の内容を取り出す
        task_content = form.task_content.data

        #登録処理
        task = Task(task_title=task_title,task_content=task_content)
        
        db.session.add(task)
        db.session.commit()
        
        #フラッシュメッセージ
        flash('課題を1件登録しました。')
        
        #一覧画面にリダイレクト
        return redirect(url_for('task.index'))
    
    #GETの場合
    return render_template('task/new_task_form.html',form=form)

#編集
@task_bp.route('/<int:task_id>/update',methods=['GET','POST'])
@login_required
def update_task(task_id):
    target_task = Task.query.get(task_id)
    
    form = TaskForm(obj=target_task)
    
    #POST時
    #バリデーションチェック
    if request.method == 'POST' and form.validate():
        #更新処理
        target_task.task_title = form.task_title.data
        
        target_task.task_content = form.task_content.data
        
        db.session.commit()
        
        #フラッシュメッセージ
        flash('課題を1件更新しました。')
        
        #一覧画面にリダイレクト
        return redirect(url_for('task.index'))
    
    #GET時
    return render_template('task/update_task_form.html',form=form,task=target_task)

#削除
@task_bp.route('/<int:task_id>/delete')
@login_required
def delete_task(task_id):
    target_task = Task.query.get(task_id)
    
    #削除処理
    db.session.delete(target_task)
    db.session.commit()
    
    flash('課題を1件削除しました。')
    
    #一覧画面にリダイレクト
    return redirect(url_for('task.index'))

#完了ボタン押下時
@task_bp.route('/<int:task_id>/complete',methods=['POST'])
@login_required
def complete_task(task_id):
    task = Task.query.get(task_id)
    task.is_completed = True
    db.session.commit()
    return redirect(url_for('task.index'))

#未完了ボタン押下時
@task_bp.route('/<int:task_id>/uncomplete',methods=['POST'])
@login_required
def uncomplete_task(task_id):
    task = Task.query.get(task_id)
    task.is_completed = False
    db.session.commit()
    return redirect(url_for('task.index'))

templates/_formhelpers.html
{% macro render_field(field) %}
    <dt>{{ field.label }}</dt>
    <dd>{{ field(**kwargs) | safe }}</dd>
    {% if field.errors %}
        <ul style="color: red;">
            {% for error in field.errors %}
                <li>{{ error }}</li>
            {% endfor %}
        </ul>
    {% endif %}
{% endmacro %}

templates/base.html
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="UTF-8">
        <title>課題管理アプリ</title>
        <link rel="stylesheet" type="text/css"  href="{{ url_for('static',filename='style.css') }}">
        <script>
            function delete_confirm(event) {
                var result = confirm("この課題を削除してよろしいですか？");
                if (result == false){
                    event.preventDefault();
                    alert("課題の削除を中止しました。");
                } else {
                    alert("課題を削除しました。");
                }
            }
        </script>
    </head>

    <body>
        {% if current_user.is_authenticated %}
            <a href="{{ url_for('auth.logout') }}">ログアウト</a>
        {% endif %}
        {% block content %}{% endblock %}
    </body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="no-complete">
        <h2>未完了：課題一覧</h2>
        {% if uncompleted_tasks != [] %}
        <ol>
            {% for task in uncompleted_tasks %}
            <div class="no-complete-tasks">
                <li>【{{ task.task_title }}】&nbsp;<a href="{{ url_for('update_task',task_id=task.id) }}">編集</a>|
                    <a href="{{ url_for('delete_task',task_id=task.id) }}" onclick="delete_confirm(event)">削除</a>
                    <br>内容・・・&nbsp;{{ task.task_content }}</li>
                <form method="post" action="{{ url_for('complete_task',task_id=task.id) }}">
                    <button type="submit" class="complete-button">完了</button>
                </form>
            </div>
            {% endfor %}
        </ol>
        {% else %}
        <p>未完了課題の登録はありません</p>
        {% endif %}
        <hr>
    </div>

    <div class="complete">
        <h2>完了：課題一覧</h2>
        {% if completed_tasks != [] %}
        <ol>
            {% for task in completed_tasks %}
            <div class="complete-tasks">
                <li>【{{ task.task_title }}】<br>内容・・・&nbsp;{{ task.task_content }}</li>
                <form method="post" action="{{ url_for('uncomplete_task',task_id=task.id) }}">
                    <button type="submit" class="uncomplete-button">未完了に戻す</button>
                </form>
            </div>
            {% endfor %}
        </ol>
        {% else %}
        <p>完了課題の登録はありません</p>
        {% endif %}
        <hr>
    </div>
    {% for message in get_flashed_messages() %}
        <div style="color: blue;">
            {{ message }}
        </div>
    {% endfor %}
    <a href="{{ url_for('new_task') }}" class="button">新規課題の登録はこちら</a>
</div>
{% endblock %}

<!--
<!DOCTYPE html>
<html>
    <head>
        <title>Task List</title>
        <link rel="stylesheet" type="text/css"  href="{{ url_for('static',filename='style.css') }}">
        <script>
            function delete_confirm(event) {
                var result = confirm("この課題を削除してよろしいですか？");
                if (result == false){
                    event.preventDefault();
                    alert("課題の削除を中止しました。");
                } else {
                    alert("課題を削除しました。");
                }
            }
        </script>
    </head>
    <body>
        <div class="container">
            <div class="no-complete">
                <h2>未完了：課題一覧</h2>
                {% if uncompleted_tasks != [] %}
                <ol>
                    {% for task in uncompleted_tasks %}
                    <div class="no-complete-tasks">
                        <li>【{{ task.task_title }}】&nbsp;<a href="{{ url_for('update_task',task_id=task.id) }}">編集</a>|
                            <a href="{{ url_for('delete_task',task_id=task.id) }}" onclick="delete_confirm(event)">削除</a>
                            <br>内容・・・&nbsp;{{ task.task_content }}</li>
                        <form method="post" action="{{ url_for('complete_task',task_id=task.id) }}">
                            <button type="submit" class="complete-button">完了</button>
                        </form>
                    </div>
                    {% endfor %}
                </ol>
                {% else %}
                <p>未完了課題の登録はありません</p>
                {% endif %}
                <hr>
            </div>

            <div class="complete">
                <h2>完了：課題一覧</h2>
                {% if completed_tasks != [] %}
                <ol>
                    {% for task in completed_tasks %}
                    <div class="complete-tasks">
                        <li>【{{ task.task_title }}】<br>内容・・・&nbsp;{{ task.task_content }}</li>
                        <form method="post" action="{{ url_for('uncomplete_task',task_id=task.id) }}">
                            <button type="submit" class="uncomplete-button">未完了に戻す</button>
                        </form>
                    </div>
                    {% endfor %}
                </ol>
                {% else %}
                <p>完了課題の登録はありません</p>
                {% endif %}
                <hr>
            </div>
            {% for message in get_flashed_messages() %}
                <div style="color: blue;">
                    {{ message }}
                </div>
            {% endfor %}
            <a href="{{ url_for('new_task') }}" class="button">新規課題の登録はこちら</a>
        </div>
    </body>
</html>
-->

templates/login_form.html
{% extends 'base.html' %}

{% block content %}
    <h1>ログイン</h1>
    {% from '_formhelpers.html' import render_field %}
        <form method="POST" action="{{ url_for('login') }}" novalidate>
            {{ form.hidden_tag() }}
            {{ render_field(form.username) }}
            {{ render_field(form.password) }}
            <br>
            {% for message in get_flashed_messages() %}
            <div style="color: blue;">
                {{ message }}
            </div>
            {% endfor %}
            {{ form.submit }}
        </form>
        <p>
            ユーザー登録がまだの方は
            <a href="{{ url_for('register') }}">こちら</a>
            から登録してください。
        </p>
{% endblock %}

templates/new_task.html
<!DOCTYPE html>
<html>
    <head>
        <title>New Task</title>
        <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='style.css') }}">
    </head>
    <body>
        <div class="container">
            <h1>新規課題の登録</h1>
            <form method="post" action="{{ url_for('new_task') }}">
                <label for="task_title">課題タイトル</label>
                <br>
                <input type="text" id="task_title" name="task_title" class="task_title_input">
                <br>
                <label for="task_content">課題内容</label>
                <br>
                <textarea name="task_content" id="task_content" cols="60" rows="5"></textarea>
                <br>
                <input type="submit" value="登録" class="button">
            </form>
            <form method="get" action="{{ url_for('index') }}">
                <input type="submit" value="課題一覧に戻る" class="return_to_index">
            </form>
        </div>
    </body>
</html>

templates/new_task_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h1>新規課題の登録</h1>
    {% from "_formhelpers.html" import render_field %}
        <form method="post" action="{{ url_for('new_task') }}" novalidate>
            {{ form.hidden_tag() }}
            {{ render_field(form.task_title) }}
            {{ render_field(form.task_content,rows=5,cols=60) }}
            {{ form.submit }}
        </form>
        <form method="get" action="{{ url_for('index') }}">
            <input type="submit" value="課題一覧に戻る" class="return_to_index">
        </form>
</div>
{%% endblock }

<!--
<!DOCTYPE html>
<html>
    <head>
        <title>New Task</title>
        <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='style.css') }}">
    </head>
    <body>
        <div class="container">
            <h1>新規課題の登録</h1>
            {% from "_formhelpers.html" import render_field %}
                <form method="post" action="{{ url_for('new_task') }}" novalidate>
                    {{ form.hidden_tag() }}
                    {{ render_field(form.task_title) }}
                    {{ render_field(form.task_content,rows=5,cols=60) }}
                    {{ form.submit }}
                </form>
                <form method="get" action="{{ url_for('index') }}">
                    <input type="submit" value="課題一覧に戻る" class="return_to_index">
                </form>
        </div>
    </body>
</html>
-->

templates/register_form.html
{% extends 'base.html' %}

{% block content %}
    <h1>ユーザー登録</h1>
    {% from '_formhelpers.html' import render_field %}
        <form method="POST" action="{{ url_for('register') }}" novalidate>
            {{ form.hidden_tag() }}
            {{ render_field(form.username) }}
            {{ render_field(form.password) }}
            <br>
            {{ form.submit }}
        </form>

        <p>
            既にアカウントをお持ちの方は
            <a href="{{ url_for('login') }}">こちら</a>
            からログインしてください。
        </p>
{% endblock %}

templates/task/index.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="no-complete">
        <h2>未完了：課題一覧</h2>
        {% if uncompleted_tasks != [] %}
        <ol>
            {% for task in uncompleted_tasks %}
            <div class="no-complete-tasks">
                <li>【{{ task.task_title }}】&nbsp;<a href="{{ url_for('task.update_task',task_id=task.id) }}">編集</a>|
                    <a href="{{ url_for('task.delete_task',task_id=task.id) }}" onclick="delete_confirm(event)">削除</a>
                    <br>内容・・・&nbsp;{{ task.task_content }}</li>
                <form method="post" action="{{ url_for('task.complete_task',task_id=task.id) }}">
                    <button type="submit" class="complete-button">完了</button>
                </form>
            </div>
            {% endfor %}
        </ol>
        {% else %}
        <p>未完了課題の登録はありません</p>
        {% endif %}
        <hr>
    </div>

    <div class="complete">
        <h2>完了：課題一覧</h2>
        {% if completed_tasks != [] %}
        <ol>
            {% for task in completed_tasks %}
            <div class="complete-tasks">
                <li>【{{ task.task_title }}】<br>内容・・・&nbsp;{{ task.task_content }}</li>
                <form method="post" action="{{ url_for('task.uncomplete_task',task_id=task.id) }}">
                    <button type="submit" class="uncomplete-button">未完了に戻す</button>
                </form>
            </div>
            {% endfor %}
        </ol>
        {% else %}
        <p>完了課題の登録はありません</p>
        {% endif %}
        <hr>
    </div>
    {% for message in get_flashed_messages() %}
        <div style="color: blue;">
            {{ message }}
        </div>
    {% endfor %}
    <a href="{{ url_for('task.new_task') }}" class="button">新規課題の登録はこちら</a>
</div>
{% endblock %}

<!--
<!DOCTYPE html>
<html>
    <head>
        <title>Task List</title>
        <link rel="stylesheet" type="text/css"  href="{{ url_for('static',filename='style.css') }}">
        <script>
            function delete_confirm(event) {
                var result = confirm("この課題を削除してよろしいですか？");
                if (result == false){
                    event.preventDefault();
                    alert("課題の削除を中止しました。");
                } else {
                    alert("課題を削除しました。");
                }
            }
        </script>
    </head>
    <body>
        <div class="container">
            <div class="no-complete">
                <h2>未完了：課題一覧</h2>
                {% if uncompleted_tasks != [] %}
                <ol>
                    {% for task in uncompleted_tasks %}
                    <div class="no-complete-tasks">
                        <li>【{{ task.task_title }}】&nbsp;<a href="{{ url_for('update_task',task_id=task.id) }}">編集</a>|
                            <a href="{{ url_for('delete_task',task_id=task.id) }}" onclick="delete_confirm(event)">削除</a>
                            <br>内容・・・&nbsp;{{ task.task_content }}</li>
                        <form method="post" action="{{ url_for('complete_task',task_id=task.id) }}">
                            <button type="submit" class="complete-button">完了</button>
                        </form>
                    </div>
                    {% endfor %}
                </ol>
                {% else %}
                <p>未完了課題の登録はありません</p>
                {% endif %}
                <hr>
            </div>

            <div class="complete">
                <h2>完了：課題一覧</h2>
                {% if completed_tasks != [] %}
                <ol>
                    {% for task in completed_tasks %}
                    <div class="complete-tasks">
                        <li>【{{ task.task_title }}】<br>内容・・・&nbsp;{{ task.task_content }}</li>
                        <form method="post" action="{{ url_for('uncomplete_task',task_id=task.id) }}">
                            <button type="submit" class="uncomplete-button">未完了に戻す</button>
                        </form>
                    </div>
                    {% endfor %}
                </ol>
                {% else %}
                <p>完了課題の登録はありません</p>
                {% endif %}
                <hr>
            </div>
            {% for message in get_flashed_messages() %}
                <div style="color: blue;">
                    {{ message }}
                </div>
            {% endfor %}
            <a href="{{ url_for('new_task') }}" class="button">新規課題の登録はこちら</a>
        </div>
    </body>
</html>
-->

templates/task/new_task_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h1>新規課題の登録</h1>
    {% from "_formhelpers.html" import render_field %}
        <form method="post" action="{{ url_for('task.new_task') }}" novalidate>
            {{ form.hidden_tag() }}
            {{ render_field(form.task_title) }}
            {{ render_field(form.task_content,rows=5,cols=60) }}
            {{ form.submit }}
        </form>
        <form method="get" action="{{ url_for('task.index') }}">
            <input type="submit" value="課題一覧に戻る" class="return_to_index">
        </form>
</div>
{% endblock %}

templates/task/update_task_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h1>課題を編集</h1>
    {% from "_formhelpers.html" import render_field %}
        <form method="post" action="{{ url_for('task.update_task',task_id=task.id) }}" novalidate>
            {{ form.hidden_tag() }}
            {{ render_field(form.task_title) }}
            {{ render_field(form.task_content,rows=5,cols=60) }}
            {{ form.update }}
        </form>
    <form method="get" action="{{ url_for('task.index') }}">
        <input type="submit" value="課題一覧に戻る" class="return_to_index">
    </form>
</div>
{% endblock %}

templates/update_task.html
<!DOCTYPE html>
<html>
    <head>
        <title>Update Task</title>
        <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='style.css') }}">
    </head>
    <body>
        <div class="container">
            <h1>課題を編集</h1>
            <form method="post" action="{{ url_for('update_task',task_id=task.id) }}">
                <label for="task_title">課題タイトル</label>
                <br>
                <input type="text" id="task_title" name="task_title" value="{{ task.task_title }}">
                <br>
                <label for="task_content">課題内容</label>
                <br>
                <textarea name="task_content" id="task_content" cols="60" rows="5">{{ task.task_content }}</textarea>
                <br>
                <input type="submit" value="更新" class="button">
            </form>
            <form method="get" action="{{ url_for('index') }}">
                <input type="submit" value="課題一覧に戻る" class="return_to_index">
            </form>
        </div>
    </body>
</html>

templates/update_task_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h1>課題を編集</h1>
    {% from "_formhelpers.html" import render_field %}
        <form method="post" action="{{ url_for('update_task',task_id=task.id) }}" novalidate>
            {{ form.hidden_tag() }}
            {{ render_field(form.task_title) }}
            {{ render_field(form.task_content,rows=5,cols=60) }}
            {{ form.update }}
        </form>
    <form method="get" action="{{ url_for('index') }}">
        <input type="submit" value="課題一覧に戻る" class="return_to_index">
    </form>
</div>
{%% endblock }


<!DOCTYPE html>
<html>
    <head>
        <title>Update Task</title>
        <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='style.css') }}">
    </head>
    <body>
        <div class="container">
            <h1>課題を編集</h1>
            {% from "_formhelpers.html" import render_field %}
                <form method="post" action="{{ url_for('update_task',task_id=task.id) }}" novalidate>
                    {{ form.hidden_tag() }}
                    {{ render_field(form.task_title) }}
                    {{ render_field(form.task_content,rows=5,cols=60) }}
                    {{ form.update }}
                </form>
            <form method="get" action="{{ url_for('index') }}">
                <input type="submit" value="課題一覧に戻る" class="return_to_index">
            </form>
        </div>
    </body>
</html>